cabal-version:   3.6
name:            cabal-tools
version:         0.1.0.0
license:         MIT
author:          andrea@andreabedini.com
maintainer:      Andrea Bedini
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall -Wno-orphans

common dependencies
    build-depends:
      , Cabal                ^>=3.12
      , Cabal-syntax         ^>=3.12
      , cabal-install        ^>=3.12
      , cabal-install-solver ^>=3.12

executable cabal-install-plan-json
    import:           warnings
                    , dependencies
    main-is:          Main.hs
    other-modules:
      Distribution.Backpack.Json
      Distribution.Simple.Json
      Distribution.Solver.Json
      Distribution.Client.Json
      Distribution.Json
      Distribution.License.Json
      Distribution.Types.Json
      Distribution.Utils.Json
      Network.Json
      Unjson
    build-depends:
        base                  >=4.14
      , aeson
      , base16-bytestring
      , binary
      , bytestring
      , containers
      , filepath
      , free
      , generic-data
      , generic-deriving
      , invariant
      , microlens
      , network-uri
      , text
      , unjson
    hs-source-dirs:   app
    default-language: GHC2021
    default-extensions:
        DerivingVia
      , LambdaCase
      , OverloadedStrings
      , ExplicitNamespaces
